name: "Check API Level"

on:
  pull_request_target:
    branches:
    - main
    - DevelNUI
    - API*

jobs:
  add-labels:
    runs-on: ubuntu-20.04
    steps:

    - name: Get Branch Metadata
      uses: TizenAPI/tizenfx-build-actions/branch-metadata@master
      id: metadata
      with:
        ref: ${{ github.base_ref }}

    - name: Add Labels
      if: ${{ steps.metadata.outputs.data }}
      uses: actions/github-script@v6
      env:
        BRANCH_METADATA: ${{ steps.metadata.outputs.data }}
      with:
        script: |
          var metadata = JSON.parse(process.env.BRANCH_METADATA)
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: metadata.labels
          })
