name: "Deploy Documents"

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        repository: TizenAPI/TizenFX-Docs

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.102'

    - name: Install DocFX Tool
      run: dotnet tool install -g docfx --version 2.61.0

    - name: Checkout TizenFX sources
      run: |
        ./build.sh clone

    - name: Cache DocFX output
      id: cache-site
      uses: actions/cache@v4
      with:
        path: _site
        key: docfx-gh-pages-site-${{ hashFiles('repos/commits') }}

    - name: Build Documents
      uses: TizenAPI/tizenfx-build-actions/problem-filter@master
      # if: steps.cache-site.outputs.cache-hit != 'true'
      with:
        run: |
          ./build.sh restore
          ./build.sh build
          ./build.sh index

    - name: Archive Artifacts
      run: |
        tar cfz site.tar.gz _site/
    - uses: actions/upload-artifact@v4
      with:
        name: documents
        path: site.tar.gz

  deploy:
    needs: [build]
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: documents

    - name: Extract Artifacts
      run: |
        tar xfz site.tar.gz
    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
        user_name: 'TizenAPI-Bot'
        user_email: 'tizenapi@samsung.com'
        full_commit_message: 'Update documents'
